### ISSUE TITLE
NameError: undefined local variable or method `skip_conversionfalse' for #<Class:0x9d1afc0>

### ISSUE THREAD

**Issue by manuelmeurer** [binarylogic/searchlogic#109]
Getting the following error after updating to 2.4.22:

NameError: undefined local variable or method `skip_conversionfalse' for #Class:0x9d1afc0

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:77:in `association_condition_options'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:19:in `method_missing'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_ordering.rb:27:in `method_missing'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/ordering.rb:30:in `method_missing'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/or_conditions.rb:28:in `method_missing'

[GEM_ROOT]/gems/activerecord-2.3.8/lib/active_record/base.rb:1994:in `method_missing_without_paginate'

[GEM_ROOT]/gems/will_paginate-2.3.14/lib/will_paginate/finder.rb:170:in `method_missing'

(eval):1:in `association_condition_options'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:56:in `eval'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:77:in `association_condition_options'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:56:in `create_association_condition'

[GEM_ROOT]/gems/searchlogic-2.4.22/lib/searchlogic/named_scopes/association_conditions.rb:16:in `method_missing'
[...]

Maybe connected to this commit?
http://github.com/binarylogic/searchlogic/commit/d4c1755080e592c63902acd62dd1688d9d0e92f3

**Comment by kwatson** [comment]
I'm seeing this same error

**Comment by aalhamad** [comment]
Seeing the same error also.

**Comment by alfuken** [comment]
Confirmed.

**Comment by kritik** [comment]
I have this only on ruby 1.8. On ruby 1.9 don't have this error

**Comment by gluecode** [comment]
+1

**Comment by kritik** [comment]
after update to 2.4.23 everything works fine
